### ISSUE TITLE
[tools] [visualstates] remove old visualStates tool and rename the new one as visualStates

### ISSUE THREAD

**Issue by okanasik** [JdeRobot/JdeRobot#1005]
The old visualStates tool is deprecated. We rename the new one from visualStates_py -> visualStates

**Comment by fqez** [comment]
Hi  @okanasik this is an awesome tool you have been working on!
I'm trying to test it in order to merge your #1006 into the repo, but I would need a list of the third-party dependencies necessary for the tool. Could you please provide me that list?

**Comment by fqez** [comment]
Nevermind, it was only missing qscintilla. ;)
