### ISSUE TITLE
VisualStates obstacleAvoidance error

### ISSUE THREAD

**Issue by vinay0410** [JdeRobot/JdeRobot#1011]
I get the following error while running,
./obstacleAvoidancePython.py obstacleAvoidancePython.yml --displaygui=true

```AttributeError: Interfaces instance has no attribute 'calculate_obstacle'```

Also, I have tested the same, using latest pull from JdeRobot Repository

**Comment by fqez** [comment]
Did you install the project in your pc?

Try running it with ```python obstacleAvoidancePython.py obstacleAvoidancePython.yml --displaygui=true```

It's working fine for me. Did you launch the associate gazebo world: ```gazebo kobuki-simple.world``` and it has binded the interfaces with the example? Gazebo should show a trace when you launch the world.
