### ISSUE TITLE
Improving ColorTuner to show color disc in GUI

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/JdeRobot#1013]
In the color disc an histogram of the current image should be shown too. This allows a better profiling of the color filters. 
And a visual definition of HSV color filters, including in a natural way color areas near the angular discontinuity (from instance from 350º to 10º in the color disc). We had this functionality in JdeRobot 4.3. release...

![colortuner2](https://user-images.githubusercontent.com/10961573/34355768-410444c4-ea38-11e7-92f8-4bf1e5d0c9ed.png)

**Comment by dattadebrup** [comment]
Hi,
I guess I will be able to implement the HSV colour disc feature as described [here](https://github.com/JdeRobot/JdeRobot/blob/4.3/schemas/hsvtuner/README). Should I work on it??

**Comment by jmplaza** [comment]
Sure, feel free to submit your Pull-Request improving the current ColorTuner tool, in python. That would be a nice contribution.

**Comment by dattadebrup** [comment]
Hi @jmplaza ,
I was working on this and I am able to make this much progress..(https://i.imgur.com/a0DFGMT.gif)
Right now I have to work on the bug where the arc is not getting drawn properly(as you can see in the gif) and then to integrate with the colortuner tool of Jderobot.Will it be alright if I submit my Pull request after 2 weeks as I have my college mid-term exams due in next week?
P.S.-I am Gsoc aspirant from India hoping to work under Jderobot.

**Comment by pushkalkatara** [comment]
@dattadebrup Are you working on this issue?

**Comment by dattadebrup** [comment]
Yes, I am...

**Comment by fqez** [comment]
Wow @dattadebrup very nice job! I can't wait to get this enhancement integrated into colorTuner! Looking very nice, keep it up!

**Comment by dattadebrup** [comment]
Thanks a lot @fqez for the appreciation.I myself can't wait to continue my work on this as soon as my exams end on Friday.

**Comment by dattadebrup** [comment]
Hi,
I successfully made the HSV color range picker.
![colorwheel-2018-02-26_16 14 50](https://user-images.githubusercontent.com/25098667/36666457-bff9d9a2-1b10-11e8-93cc-d965f8c466ab.gif)
But I was having a hard time while trying to integrate it with the colortuner tool. Here is the [code](https://gist.github.com/dattadebrup/31491a8205b056f7c821015857a68213) of the standalone python file and the color disc image [file](https://i.imgur.com/wkQ8j9W.png) (rename it as wheelfinal.png after downloading the image) required to be kept in the same directory as the .py file. Can anyone please guide me how to integrate with the colortuner tool?

**Comment by dattadebrup** [comment]
Hi,
I managed to integrate it with the colorTuner tool succesfully. Please review the PR. #1091

**Comment by aitormf** [comment]
solved #1091
