### ISSUE TITLE
Better world and car plugin for "STOP exercise" in JdeRobot-Academy

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/JdeRobot#1019]
This exercise is broken. It works for @ilope236 [video](http://jderobot.org/Teaching_robotics_with_JdeRobot#Stop_at_a_T_joint), but the infrastructure is not well integrated on official JdeRobot repository yet

**Comment by fqez** [comment]
solved in f74ba5e991b1c7e22303716763828daf3947c7f5
