### ISSUE TITLE
[Gazebo] Add support for MBOT grip

### ISSUE THREAD

**Issue by fqez** [JdeRobot/JdeRobot#1033]
To complete the robot hardware, it is a good idea to add as many sensors/actuators as possible so we can make many different exercises. The grip would bring us dozens of new examples to explode.

This is the MBOT grip:

![image](https://user-images.githubusercontent.com/8070644/35162480-d355454e-fd43-11e7-89df-56e98b131472.png)

![image](https://user-images.githubusercontent.com/8070644/35162491-d94f992c-fd43-11e7-8fe6-21aea36dc176.png)

It does include a servo.

**Comment by aitormf** [comment]
mBot plugin is no longer in this repository
