### ISSUE TITLE
having problems in installation of jderobot

### ISSUE THREAD

**Issue by kpranav1998** [JdeRobot/JdeRobot#1036]
Dear Sir,
              Sir i have been facing issues in installing Jderobot.I am mainly getting three errors

1)"ImportError: No module named Ice".This  error is always showing when i try to compile with python2.7.
2)I am unable to run the python dependencies of jderobot with python3.5.I went to the following file   "/opt/jderobot/setup.bash"  .I changed the python path to
 "export PYTHONPATH=$PYTHONPATH:/opt/jderobot/lib/python3.5"
from "export PYTHONPATH=$PYTHONPATH:/opt/jderobot/lib/python2.7"
.But still i am getting errors.
3)"ImportError: No module named jderobot".This error is also coming

**Comment by jmplaza** [comment]
It seems from [this thread on Answers](http://answers.jderobot.org/question/59/problem-in-installation-of-jderobot/) that this problem was solved after a reinstallation on a clean machine.
