### ISSUE TITLE
[Tools][VisualStates_py] Access to interfaces inside time transitions

### ISSUE THREAD

**Issue by reysam93** [JdeRobot/JdeRobot#1064]
With the current state of the tool, time transitions do not have access to the interfaces object. This would be useful because it is posible to execute code when the transition is activated, and the interfaces object has variables that are common to the rest of the automata, so with this modification the time transitions will be able to modify these variables when they have been activated.

**Comment by jmplaza** [comment]
This will be solved on the VisualStates [new repository](https://github.com/JdeRobot/VisualStates/issues/6)
