### ISSUE TITLE
RGBD example: Xtion + openniserver + RGBDviewer tool is broken

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/JdeRobot#1072]
This example, explained in [the web](http://jderobot.org/index.php/Examples#OpenniServer_.2B_RGBDViewer_.2B_Asus_Xtion), is broken. When launching the server:

>  mybash> openniServer openniServer.cfg
openniServer: error while loading shared libraries: libOpenNI2.so: cannot open shared object file: No such file or directory

**Comment by igarag** [comment]
Tested: the configuration file is.yml and not.cfg as shown in the tutorial. Changed in the tutorial description.
