### ISSUE TITLE
[Tools][VisualStates] Edit config files

### ISSUE THREAD

**Issue by reysam93** [JdeRobot/JdeRobot#1076]
Now, when creating the configuration file using Visual States is possible to add a new interface or to remove an existent one. It would be useful to edit the existing interfaces also, allowing to modify its fields and save it. Right now, the only way to do this is create a new interface with the desired fields and remove the old one.

**Comment by pushkalkatara** [comment]
Hi @reysam93 . I would like to work on the issue.  My approach would be -

- [] Create new QPushButton "Edit" at column8 beside delete button.
- [] Create new function editClicked() which would open QInputDialog to take new config data.
- [] Update the configData and the QLabel.

**Comment by jmplaza** [comment]
This will be solved on the VisualStates [new repository](https://github.com/JdeRobot/VisualStates/issues/5)
