### ISSUE TITLE
[Gazebo] New world with mobile parts

### ISSUE THREAD

**Issue by fqez** [JdeRobot/JdeRobot#1112]
It's a good a idea to add a simulated world in gazebo emulating a gymkhana for drones in order to make the drone porgramming challenge (program-A-robot).

**Comment by abhayraw1** [comment]
So, the mobile parts or obstacles would have a predefined trajectory or random?

**Comment by fqez** [comment]
Hi there's already a first approach of this issue in the gymkhana branch of the repo, but it does need another iteration fixing:

* Collision with the moving walls, they should have more mass and an inertia matrix defined (default matrix is fine tho)

* Collisions with the hangar walls and roof, because it only has collision with the ground

* Moving walls need different color and (if possible) textures. Current colors are difficult to distinguish with the environment.

Here's a video showing the current state of the branch: https://www.youtube.com/watch?v=c9y89vZVkjg

Feel free to modify whatever you consider necessary :)

**Comment by abhayraw1** [comment]
Thanks, I'll give it a shot.

**Comment by fqez** [comment]
About the trajectory I would make it random to make this more fun. The current implementation consists on a dummy plugin for each wall moving them linearly. Let me know if you face any problem with this! good luck!

**Comment by abhayraw1** [comment]
Hey, is the branch updated, because I see that `gazebo.world` only includes models for the hanger and the sun. 
We must also include a drone also, right?
Also I cant seem to see any inertial matrix defined.

**Comment by fqez** [comment]
Hi, no there's no drone included in the world, I added it manually to record the video, but yeah, you can include it in the file with your changes! (its name is ArDrone2). About the inertial matrix, they are not included in the current version, that's why this issue needs another iteration.

**Comment by abhayraw1** [comment]
No issues. I had already added those file. Was going to push them in the update. 

Is it okay if i change the meshes for the walls to some modified version of a basic cube?
