### ISSUE TITLE
[Drivers] Cameraserver-web doesn't work with USB Cameras

### ISSUE THREAD

**Issue by aitormf** [JdeRobot/JdeRobot#1149]
When I try to use this driver with USB webcams, I get following error:

![image](https://user-images.githubusercontent.com/16046048/39619141-f81da23c-4f86-11e8-96ac-d168473cf9f0.png)
 with internal webcams all OK

**Comment by aitormf** [comment]
I'm using this driver with in Browser mode and all works fine. It seems a problem with electron api

**Comment by jmplaza** [comment]
Hi @aitormf, I think that @rperezgonz has worked on this and has a solution for it.
