### ISSUE TITLE
[drivers] Support for IR sensor reading (leerIRSigueLineas) on real PiBot

### ISSUE THREAD

**Issue by fgonzalezr1998** [JdeRobot/JdeRobot#1223]
I've seen is not programmed the follow lines function at pibot.py for the real PiBot. I'm taking care of doing it, ok? I'm programming it similar than pibot.py for gazebo

**Comment by jmplaza** [comment]
Hi @fgonzalezr1998 better that the follow-line function, it would be better to provide the functions to access the required sensors if they are not already included. Follow-line is a behavior and so it should not be included in the driver for PiBot, it is just an exercise on JdeRobot-Kids set. The driver only contains the functions to access to robot sensors and robot actuators.

**Comment by jmplaza** [comment]
Ok @fgonzalezr1998, I got it now. The idea is to provide support for reading values of two IR sensors looking downwards in the real PiBot. They are supported in the simulated PiBot, but not yet in the real one. This support is quite convenient for the follow-line behavior. I rename the issue accordingly.
