### ISSUE TITLE
[deb package] JdeRobot apt installation fails

### ISSUE THREAD

**Issue by naxvm** [JdeRobot/JdeRobot#1295]
Hi,

The JdeRobot installation via deb package (through apt) fails, due to the announcement of the 5.6.5 ( http://jderobot.org/apt/pool/main/j/jderobot-examples/jderobot-examples_5.6.5_all.deb) version from the JdeRobot source: `apt update`yields "Des:68 http://jderobot.org/apt xenial/main amd64 jderobot all 5.6.5".

Can we roll back the published .deb to 5.6.4 until the new version is online?

**Comment by fqez** [comment]
Hi Nacho,

it seems that the upload of that pagkage failed when I updated the repo. It should be solved now.

Thanks for the report.
