### ISSUE TITLE
[APT] jderobot-gazebo-assets (version 5.6.7)

### ISSUE THREAD

**Issue by naxvm** [JdeRobot/JdeRobot#1303]
```apt upgrade```fails due to a 5.6.7 version available on the <code>jderobot-gazebo-assets</code> package on the APT repository. dpkg fails due to a broken file. The output log for the command (in a foreign language I don't understand):

> $ sudo apt upgrade
> Leyendo lista de paquetes... Hecho
> Creando árbol de dependencias       
> Leyendo la información de estado... Hecho
> Calculando la actualización... Hecho
> Se actualizarán los siguientes paquetes:
>   jderobot-gazebo-assets
> 1 actualizados, 0 nuevos se instalarán, 0 para eliminar y 0 no actualizados.
> Se necesita descargar 0 B/346 MB de archivos.
> Se utilizarán 552 MB de espacio de disco adicional después de esta operación.
> ¿Desea continuar? [S/n] 
> (Leyendo la base de datos ... 509764 ficheros o directorios instalados actualmente.)
> Preparando para desempaquetar .../jderobot-gazebo-assets_5.6.7_amd64.deb ...
> Desempaquetando jderobot-gazebo-assets (5.6.7) sobre (5.6.6) ...
> dpkg: error al procesar el archivo /var/cache/apt/archives/jderobot-gazebo-assets_5.6.7_amd64.deb > (--unpack):
>  sistema de ficheros del archivo tar dañado - archivo de paquete dañado
> dpkg-deb: error: el subproceso copiado fue terminado por la señal (Tubería rota)
> Se encontraron errores al procesar:
>  /var/cache/apt/archives/jderobot-gazebo-assets_5.6.7_amd64.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by aitormf** [comment]
fixed with last package of jderobot-gazebo-assets
