### ISSUE TITLE
Refactor openniServer video-mode selection

### ISSUE THREAD

**Issue by chanfr** [JdeRobot/JdeRobot#131]
In the new xtion device video mode on depth and rgb sensor are not the same so we need to include an independent selection mode.

**Comment by fqez** [comment]
Hi @chanfr is this issue closeable? There's a video mode selection already in OpenniServer (https://github.com/RoboticsURJC/JdeRobot/blob/master/src/stable/drivers/openniServer/openniServer.cfg#L14-L18)
