### ISSUE TITLE
ROS-JdeRobot compatibility library (drivers for a typical Pioneer robot)

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/JdeRobot#179]
In order to increase the compatibility between ROS framework and JdeRobot it is interesting to wrap the ROS nodes acting as drivers (for sensors or actuators) and let them provide their data as ICE messages. This way a JdeRobot application, consisting of one or several components, may connect to ROS drivers to get sensor data, or to command orders to actuators. This is particularly useful to use drivers from the ROS community inside JdeRobot applications.

The wrapping should also work in the reverse direction, a ROS application (set of nodes) should may use a JdeRobot component as driver. The wrapping should provide the data from the ICE interfaces as topics for the ROS nodes.

Let's start with the common JdeRobot interfaces for a wheeled robot (laser sensor, pose3D for odometry, motors, cameras) and the interfaces for RBGD devices (depth image, pointclouds...). Achieving this we would have a 'common' Hardware Abstraction Layer between ROS and JdeRobot.

**Comment by fqez** [comment]
solved at #683
