### ISSUE TITLE
 ROS-JdeRobot compatibility: using rosbag files in JdeRobot

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/JdeRobot#180]
Another step to increase the interaction between both robot frameworks is extending JdeRobot to read data from the bag files of ROS. ROS uses rosbag (former tools rosrecord and rosplay) for storing sensor data and read them. In JdeRobot we have the recorder and replayer components for that. These tools work with an own file format for the log files. There is a huge set of data files in the ROS community, and it is interesting to use them from our JdeRobot applications. For instance benchmarks with data from RGBD sensors.

**Comment by aitormf** [comment]
this issue is the same that #566
