### ISSUE TITLE
Change the interface name of some tools

### ISSUE THREAD

**Issue by fqez** [JdeRobot/JdeRobot#238]
We have some tools with "wrong" interface name prefix. For example, the colorTuner tool has this in its .cfg file:

```
Cameraview.Camera.Proxy=cameraA:tcp -h localhost -p 9998
```

instead of

```
ColorTuner.Camera.Proxy=cameraA:tcp -h localhost -p 9998
```

**Comment by varhub** [comment]
About this, I will propose a little different movement. So just hang on.
I you want a spoiler, here you are: http://jderobot.org/Varribas-tfm/libiceconfigresolver
