### ISSUE TITLE
Reformat opencvdemo component

### ISSUE THREAD

**Issue by ojgarciab** [JdeRobot/JdeRobot#27]
I would like to fix, as an exercise/practice, this:

Syntax and language refactoring:
- [x] Correct syntax as proposed ([Google C++ Style Guide](https://google-styleguide.googlecode.com/svn/trunk/cppguide.html)).
  - [x] Convert real tabs in 2 space characters.
  - [x] Variable names: lower case, only underscore as separator and be descriptive.
  - [x] Class members: add trailing slash.
  - [x] Function names: should start with a capital letter and have a capital letter for each new word without underscores.
- [x] Fixing OpenCV code:
  - [x] Remove `using namespace cv;` (it is a bad practice).
  - [x] Add cv:: prefix to all OpenCV functions/clases.
  - [x] Fix old naming conventions (C styled OpenCV, as `cvLine` -> `cv::line`).
  - [x] Remove all instance destructors managed by OpenCV's automatic memory management.
- [x] Remove unused dependencies in cmake.

Comments and learning value of them:
- [x] Delete old comments holding unused code.
- [x] Add new comments to aid new developers:
  - [x] Descriptive comments.
  - [x] References to OpenCV manual.

New enhancements:
- [x] Fixing glade "IDs".
- [x] Fix convolution code.
- [x] Let glade XML set initial visible state, and not viewer constructor.
- [x] Remove unused code.
- [x] Fix filter order to let Gaussian Blur do it's job before Color Filter, Pyramid before all others, ect.
- [x] Reorder code for readability and/or optimize tasks as show/hide glade blocks.
- [x] Inmunize code against common network errors:
  - [x] Initial connection for proxy creation.
  - [x] Connection issues like timeout (remote server offline) and connection refused (remote server online but remote ice endpoint not running).
- [x] Add support for more image formats:
  - [x] Support for GRAY8 (grey scale).
  - [x] Support for NV21 (AndroidCameraServer).
  - [x] Refactor image conversion to RGB8 using `colorspaces`.
- [x] Add Doxygen support for automatic documentation generation.

Best regards.

**Comment by ojgarciab** [comment]
First problem found: [The #define Guard](https://google-styleguide.googlecode.com/svn/trunk/cppguide.html#The__define_Guard)

>All header files should have #define guards to prevent multiple inclusion. The format of the symbol name should be <PROJECT>_<PATH>_<FILE>_H_.
>
>To guarantee uniqueness, they should be based on the full path in a project's source tree. For example, the file foo/src/bar/baz.h in project foo should have the following guard:
>
>     #ifndef FOO_BAR_BAZ_H_
>     #define FOO_BAR_BAZ_H_
>     
>     ...
>     
>     #endif  // FOO_BAR_BAZ_H_

So `src/stable/components/opencvdemo/viewer.h` header file should be:

```
#ifndef JDEROBOT_STABLE_COMPONENTS_OPENCVDEMO_VIEWER_H_
#define JDEROBOT_STABLE_COMPONENTS_OPENCVDEMO_VIEWER_H_

...

#endif  // JDEROBOT_STABLE_COMPONENTS_OPENCVDEMO_VIEWER_H_
```

It looks so large... but for now I'll use that guard format.

**Comment by abhinavjain241** [comment]
I think I can work on fixing this issue. I'll send a pull request in 1-2 days once I'm done re-factoring the source code.

**Comment by ojgarciab** [comment]
I'm working on it right now. It's almost finish.

**Comment by abhinavjain241** [comment]
Oh okay okay, thats fine. I'd love to help by suggesting enhancements :)

**Comment by ojgarciab** [comment]
Your enhancements are welcome.

I just have done some code optimizations to immunize it about common network errors (time out when remote server are offline and connection refused when remote server is online but ice endpoint is not running).

When I finish this refactorize you could add your own code to enhance it :)

**Comment by ojgarciab** [comment]
I added support to every image format supported by `colorspaces::Image`, included NV21 (for android devices). Before that update only `RGB8` format was supported by `opencvdemo`.

**Comment by aitormf** [comment]
Can I close this issue @ojgarciab ??

**Comment by ojgarciab** [comment]
Your can close it, it is too old and it's too late to merge changes.
