### ISSUE TITLE
Integration of Kinect2 driver

### ISSUE THREAD

**Issue by fqez** [JdeRobot/JdeRobot#277]
Due to the installation of the dependencies for kinect2server are not automatic at all, I'm going to try to integrate them into the installation process from debían packages. We may need to add at least one third party .deb in the deps list and one new repository to make the installation plausible.

**Comment by jmplaza** [comment]
@chanfr got it working as can be seen in this [video](http://jderobot.org/Frivas-phd#kinect2Server)
