### ISSUE TITLE
Bug with the generated /usr/lib/python2.7/jderobot/__init__.py file

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/JdeRobot#338]
It generates an almost empty __init__.py file, without the modules for ICE interfaces. And then, the python JdeRobot component fail to use the ICE interfaces.

**Comment by fqez** [comment]
Fixed with the new packages v5.3.1-rc4

**Comment by fqez** [comment]
Weird problem, it's correct in the CMakeLists installation proccess, but it still does copy the wrong file. I think it has something to do with cmake and installing existing files. Is there a way to override existing files in the cmake INSTALL command @lr-morales? I thinks that's the problem...
