### ISSUE TITLE
VisualHFSM use environment preparation needed

### ISSUE THREAD

**Issue by fqez** [JdeRobot/JdeRobot#373]
VisualHFSM uses some special folders in order to be used, as shown: [here for python](https://github.com/reysam93/TFG/blob/master/instruccionespy.txt) and [here for c++](https://github.com/reysam93/TFG/blob/master/instruccions.txt). So a CMakeLists.txt change is needed in order to apply these directives.

**Comment by reysam93** [comment]
I have created a script: [setup.sh](https://github.com/reysam93/JdeRobot/blob/master/src/stable/tools/visualHFSM/setup.sh) that create this folders and copy the files needed. The ideal solution would be that this script is automatically executed when installing the tool.

**Comment by aitormf** [comment]
solved with #902
