### ISSUE TITLE
Wrong detection of the pioneer color in the ardrone-turtle.world

### ISSUE THREAD

**Issue by reysam93** [JdeRobot/JdeRobot#390]
When launching the world ardrone-turtlebot.world, the pioneer is represented with the top green and blue, but when I start using the drone's camera, the camera do not detect this colors. There is attached an image of how it looks. I have tried it using the turtlebotJde2cam, the turtlebotJde, the Ardrone2 and the Ardrone, but non of them works.

![bugfollowturtle](https://cloud.githubusercontent.com/assets/10724295/13949004/6430d220-f023-11e5-9793-2036bcf4c897.png)

**Comment by fqez** [comment]
Try the new world ardrone-turtlebot_transparent.world. Should solve your problem. Remember to copy the new model ground_plane_transparent too to ~/.gazebo/models

Cheers

**Comment by reysam93** [comment]
I have tried it and still does not work properly. As you can see in the picture, looks like the green zone over the robot is transparent, the camera can only see the borders.
![bugkubuki](https://cloud.githubusercontent.com/assets/10724295/14185518/84d76210-f77a-11e5-80be-f530943f0de9.png)

**Comment by fqez** [comment]
It seems like the model is colliding with the tag as happened with the ground. We have two options here, make the turtlebot model transparent too, or review the tag. I will take a look to the tag and play with different textures.

**Comment by artuvd** [comment]
I have the same problem! I've tried ardrone-turtlebot_transparent.world too, with the same result that reysam93. It seems like the tag is transparent under the bot is, in other tag parts the camera detects it.

**Comment by fqez** [comment]
Yes, I tried multiple solutions here, but no one seems to work. I think is a render issue from the gazebo cameras, but it's not characterized yet. We will update our dependencies to gazebo 7 so we can test there if this issue is solved. If not, I will give another try to this problem. 

Sorry for the inconvenience.

**Comment by fqez** [comment]
I've tried again in a Ubuntu 14.04 64-bit native machine and works for me and for @aitormf. Are you using a virtual machine?

Here there is two examples testing this issue

* With uav_viewer

![ardrone-visual](https://cloud.githubusercontent.com/assets/8070644/17137544/00112b9c-533c-11e6-99b5-83698e954d0b.png)

* With introrob_py

![captura de pantalla de 2016-07-26 14_17_47](https://cloud.githubusercontent.com/assets/8070644/17137571/201a5ad0-533c-11e6-9ab7-b4304ca9301f.png)

both of them running on native systems.

**Comment by artuvd** [comment]
I had before a virtual machine (in Parallels) and it worked perfectly. Now i've prepared a physical machine, a HP-Compaq CQ-70, running ubuntu 14.04 LTS, and it hasn't any other OS installed, it's dedicated exclusively to this proyect.

**Comment by aitormf** [comment]
Close this issue because actually works well: 

![captura de pantalla de 2017-05-12 10-53-32](https://cloud.githubusercontent.com/assets/16046048/25990815/67b19080-3701-11e7-93fe-a3d0ca440703.png)
