### ISSUE TITLE
portability: test of 'Simulated ArDrone + UAVViewer' example from Windows

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/JdeRobot#419]
One attractive feature is portability, to use JdeRobot from other Operating Systems. Docker may help on this. Let's do a first test running part of the  'Simulated ArDrone + UAVViewer' example [http://jderobot.org/index.php/Running_JdeRobot#Simulated_ArDrone_.2B_UAVViewer] on a Windows machine. Gazebo will run on a Linux machine as usual, but the uavviewer component should run on a Windows machine.

**Comment by aitormf** [comment]
this issue is resolved with #543
