### ISSUE TITLE
Missing library ICE-JS in JdeRobot dependencies

### ISSUE THREAD

**Issue by aitormf** [JdeRobot/JdeRobot#425]
Missing library ICE-JS in JdeRobot dependencies. It allows servers to use the WebSocket protocol required for web clients. Currently cannot be used without first going to my repository to download it.

Tests that do not come into conflict with any JdeRobot component should be made

**Comment by fqez** [comment]
Which exact library is missing?

**Comment by aitormf** [comment]
To use the webTools, need to install the IceWS (from IceJS) plugin for servers ICE can use the WebSocket Protocol. To do this we need to follow the instructions I have on my [MediaWiki](http://jderobot.org/Aitormf-tfg#IceJS) but I think that this installation should be within the premises of JdeRobot.
