### ISSUE TITLE
[drivers] Quadrotor2 plugin now depends on Quadrotor plugin

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/JdeRobot#457]
and should be self-contained. Quadrotor old plugin will be replaced by the new (better) release and deleted from the repository.

**Comment by aitormf** [comment]
I do not see this dependence, I've been looking at the code and  CMakelist.txt and it does nothing. It may seem by how the files are sorted but not depends on quadrotor. And you can compile quadrotor2 without quadrotor

**Comment by almartinflorido** [comment]
Hi @aitormf ,

I think that @jmplaza  refers to this [1], the meshes and materials of ArDrone2 referenced to ArDrone. The idea is remove ArDrone model and plugin. Furthermore, the model ArDrone has meshes do not correspond with the quadrotor [2].

regards

[1]: https://github.com/RoboticsURJC/JdeRobot/blob/master/src/stable/drivers/gazeboserver/models/ArDrone2/model.sdf
[2]:https://github.com/RoboticsURJC/JdeRobot/tree/master/src/stable/drivers/gazeboserver/models/ArDrone/meshes
