### ISSUE TITLE
Laser in the world kobuki-simple.world doesn't see well

### ISSUE THREAD

**Issue by aitormf** [JdeRobot/JdeRobot#476]
Laser in the gazebo world kobuki-simple.world doesn't see well. Its representation does not adpat what the sensor receives:

![error_laser_gazebo](https://cloud.githubusercontent.com/assets/16046048/15742065/0b0381fc-28bd-11e6-9054-b2ccd4a51412.png)

**Comment by fqez** [comment]
Hmmm weird... it happens every time you run the example? or is this an isolated case? It happened to me before, but after a while doing bad things with the robot (like high-speed bumping with the walls, high-speed spinning, etc)

**Comment by aitormf** [comment]
This bug will be fixed when we jump to gazebo 7

**Comment by fqez** [comment]
Solved with gazebo 7
