### ISSUE TITLE
Pose3D position fails in kobuki_driver

### ISSUE THREAD

**Issue by fqez** [JdeRobot/JdeRobot#507]
The x, y position given by kobuki_driver grows even with the robot standing still. This problem comes from the low level layer of the driver.

**Comment by aitormf** [comment]
I have located the problem: kobuki_driver does not receive well pose from odometry.

I have actualized kobukilib versión from 0.3x to 0.71 and I see the same. I'm going to study well the examples from yujing to try to fix it.
