### ISSUE TITLE
5.3.3 version not includes shared libraries

### ISSUE THREAD

**Issue by aitormf** [JdeRobot/JdeRobot#515]
I just update JdeRobot to 5.3.3 version by apt-get in Ubuntu 14.04 (installation size: 6 Mb) and it not includes shared libraries:

![captura de pantalla de 2016-07-04 09 54 30](https://cloud.githubusercontent.com/assets/16046048/16554264/ecc75612-41cd-11e6-8f25-e03c13f58efa.png)

**Comment by fqez** [comment]
Working on it >.<

**Comment by fqez** [comment]
should be fixed now!
