### ISSUE TITLE
Delete --Ice.Config flag in components

### ISSUE THREAD

**Issue by aitormf** [JdeRobot/JdeRobot#524]
It is good idea to not have to use the flag --Ice.Config to add the configuration file of components. Just need to add the configuration file without flag

Tools:

- [x] 3DViewer
- [x] basic_component
- [x] basic_component_py
- [x] cameraCalibrator
- [x] cameraview
- [x] colorTuner
- [x] giraffeClient
- [x] kobukiViewer
- [x] namingService
- [ ] naoviewer
- [x] navigatorCamera
- [x] opencvdemo
- [x] recorder2
- [x] replayController
- [x] replayer2
- [x] rgbdCalibrator
- [x] rgbdManualCalibrator
- [x] rgbdViewer
- [x] uav_viewer
- [x] visualHFSM

Drivers:

- [x] MAVLinkServer
- [x] ardrone_server
- [x] basic_server
- [x] cameraserver
- [ ] giraffeServer
- [x] kinect2server
- [x] kobuki_driver
- [x] laser_server
- [ ] naoserver
- [x] openni1Server
- [x] openniServer
- [x] pclRGBDServer

**Comment by fqez** [comment]
Isn't it better to wait till we decide how to parse files first? So you can make the changes all together instead of refactor them twice!

**Comment by aitormf** [comment]
I have found a way easy of do it and is modify the part of load the properties in easyconfig, so accept both flag as not. So we should only add easyconfig to components that do not have it

**Comment by jmplaza** [comment]
If it is so easy to have this functionality, let's put it now to start enjoy it, no?. Launching components will be even more easy and intuitive than now.
