### ISSUE TITLE
[Deps] Package jderobot-deps-dev don't install Ice 3.6 for python

### ISSUE THREAD

**Issue by aitormf** [JdeRobot/JdeRobot#603]
Package jderobot-deps-dev hasn't post install script to innstall ICE 3.6 for python with pip

**Comment by fqez** [comment]
I'm trying to fix this ASAP. Meanwhile you can follow the steps from the manual for [ICE 3.6 installation](http://jderobot.org/Manual-5#Manual_installation_of_JdeRobot_.28for_the_brave.29)

     sudo pip3 install --upgrade pip
     sudo pip3 install zeroc-ice

Sorry for the inconvenience.

**Comment by fqez** [comment]
Done
