### ISSUE TITLE
[examples] kobuki-simple.world + kobukiviewer example is broken

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/JdeRobot#637]
Gazebo starts fine, but kobukiviewer fails. Here are the shell messages:
jmplaza@papageno:~$ kobukiViewer kobukiViewer.cfg
[Info] loaded Ice.Config file: /usr/local/share/jderobot/conf/kobukiViewer.cfg
Pose3D connected
Camera1 connected
Outgoing.cpp:478: Ice::ObjectNotExistException:
object does not exist:
identity: `cameraR'
facet:
operation: ice_isA
!! 21/11/16 18:17:50.439 error: communicator not destroyed during global destruction.terminate called after throwing an instance of 'IceUtil::ThreadSyscallException'
  what():  ../../include/IceUtil/Mutex.h:303: IceUtil::ThreadSyscallException:
syscall exception: Invalid argument
Aborted (core dumped)

This happens in a machine with a clean installation of ubuntu 16.04, no previous version of ICE communication middleware was installed.

**Comment by aitormf** [comment]
It is a small bug in config file. 
 It will be solved Changing `cameraR` by `CameraR`
