### ISSUE TITLE
[Gazebo] Test RCL (ROS Compat. Lib.) with simulated kobuki + kobukiViewer

### ISSUE THREAD

**Issue by fqez** [JdeRobot/JdeRobot#640]
In order to take advantage of the RCL (ROS Compatibility Library), we have to make kobukiViewer tool bilingual (issue #551) and test it with the modified ROS plugins for the turtlebot

**Comment by aitormf** [comment]
[![kobukiViewer receiving laser from  simulated kobuki ROS(https://img.youtube.com/vi/5iHeSBbzDRk/0.jpg)](https://www.youtube.com/watch?v=5iHeSBbzDRk)

**Comment by aitormf** [comment]
We can see complete compatibility:
[![Billingual kobukiViewer ](https://img.youtube.com/vi/PccTxiCs1cA/0.jpg)](https://www.youtube.com/watch?v=PccTxiCs1cA)
