### ISSUE TITLE
[drivers] New Formula1 race circuit, similar to Montecarlo one

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/JdeRobot#690]
It will be used in several exercises of [Teaching Robotics](http://jderobot.org/Teaching_robotics_with_JdeRobot#Exercises_on_autonomous_cars)

@kb8alvaro has built good prototypes for this, check them at his [webpage](http://jderobot.org/Avillamil-tfg)

![image](https://cloud.githubusercontent.com/assets/10961573/23175976/7fcc6d4a-f861-11e6-8fe4-15bbeaf8a1cb.png)

**Comment by kb8alvaro** [comment]
It is done!! Just waiting to know how to do the pull request and I'll upload so you can race :)
![monacoplano8](https://cloud.githubusercontent.com/assets/9249369/23699185/817796cc-03ee-11e7-9564-8a97923555b2.png)

**Comment by fqez** [comment]
Hi @kb8alvaro !

you have the instructions to make your own pull requests here: https://github.com/JdeRobot/JdeRobot/wiki/How-To-Contribute

**Comment by jmplaza** [comment]
Hi, I've tested the world in JdeRobot-5.5 and the Monaco circuit just falls down as shown in this [video](https://youtu.be/z7bj_QdEWMQ)

**Comment by aitormf** [comment]
merged #724
