### ISSUE TITLE
[Tools] Replace colorTuner C++ for ColorTuner_py

### ISSUE THREAD

**Issue by aitormf** [JdeRobot/JdeRobot#692]
I have been thinking that we could delete colorTuner C++ because is has many problems like #238, #246, #409, #416. In adition it uses GTK GUI and we are changing GTK for QT in all tools,...

for the other hand, ColorTuner_py works well and hasn't any of those problems

**Comment by fqez** [comment]
I agree with @aitormf

**Comment by jmplaza** [comment]
Perfect, let's get rid of colorTuner (C++) and replace it by ColorTuner_py. For those users that are willing to see an example of C++ program using OpenCV, they can see it in OpenCVdemo tool.
