### ISSUE TITLE
[Deps] Prepare dependencies for JdeRobot 5.5

### ISSUE THREAD

**Issue by aitormf** [JdeRobot/JdeRobot#708]
We are preparing the jump to Jderobot 5.5 with changes as ROS compatibility. This compatibility fores us to downgrade in some dependencies and upgrade in other:

- python 3 -> python 2.7
- pcl (point cloud library) 1.8 -> pcl 1.7
- vtk 7 -> vtk 6.2 
- opencv 3.1 -> opencv 3.2

the advantage is that we kept pcl, vtk and opencv and now we don't need to do it

**Comment by jmplaza** [comment]
Cool!. With no need to generate ourselves those packages, we can focus on other tasks
