### ISSUE TITLE
Refactor jderobot logging system to use Google Logs

### ISSUE THREAD

**Issue by chanfr** [JdeRobot/JdeRobot#730]
The idea is to move from jderobot::Logging to glogs in order to use all the functionality included in this logging library.  

Doc:
http://rpg.ifi.uzh.ch/docs/glog.html

Repo:
https://github.com/google/glog

**Comment by aitormf** [comment]
I like the idea

**Comment by chanfr** [comment]
#754 Includes google logs

But
#737 Is required before this merge

**Comment by chanfr** [comment]
New pull requests:
#762
