### ISSUE TITLE
[drivers] YouTubeServer: getting images from YouTube web page

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/JdeRobot#739]
a new component that accepts in its configuration file the URL of a video in YouTube webpage and gets the frames of such video through the standard Image-Camera interface would be great. It would allow to connect all the JdeRobot computer vision applications to YouTube videos.

**Comment by apavo** [comment]
Hi,
Yes, i'm using youtube-dl for extract the video link. Mainly we are developing it for Youtube, but 
But should be compatible with other video services too.
