### ISSUE TITLE
[tools] mainwindow.ui of Uav_viewer is deprecated

### ISSUE THREAD

**Issue by aitormf** [JdeRobot/JdeRobot#775]
as I said @shivangg in #660: 
`uav_veiwer/gui/mainwindow.ui` seems to be depreciated because running `uic` generates `ui_mainwindow.h` that is different from the `uav_viewer/gui/ui_mainwindow.h` . `velBox` and `dataBox` are misssing. `mainwindow.ui`should be updated to the suitable version (to the one that generated the current `ui_mainwindow.h` ) to finally add the Jderobot icon.

**Comment by jmplaza** [comment]
The whole uavviewer in C++ is going to be marked as deprecated. Instead, the preferred release of this tool will be its python version, which has been recently improved through the #702 issue
