### ISSUE TITLE
[Tools] [visualHFSM] generated code will use new jderobot communication framework

### ISSUE THREAD

**Issue by okanasik** [JdeRobot/JdeRobot#842]
Generated code will use new jderobot communication framework. Currently, the tool creates ICE proxies selected from the interfaces dropdown. However, new jderobot communication framework can work both with ICE proxies and also with ROS topics. We aim to change python and c++ code templates to work with new jderobot communication framework.

**Comment by jmplaza** [comment]
Solved in #902
