### ISSUE TITLE
[libs] [jderobotcomm] Jderobotcomm client classes throws "ERROR: ROS is not available" exception even if ROS_cpp is found

### ISSUE THREAD

**Issue by okanasik** [JdeRobot/JdeRobot#867]
Jderobotcomm client classes throws "ERROR: ROS is not available" exception even if ROS_cpp is found. throwing exception part should in #else of the ifdef part.

**Comment by aitormf** [comment]
Hi @okanasik, 
This exception is thrown when you launch the clients without launching roscore before.

**Comment by okanasik** [comment]
Hi @aitormf, I checked the code again, but i see that code always throws error whether or not roscpp is defined or roscore is running. You can check this line: https://github.com/JdeRobot/JdeRobot/blob/master/src/libs/jderobotcomm_cpp/src/cameraClient.cpp#L51

**Comment by aitormf** [comment]
You're right @okanasik
