### ISSUE TITLE
[Tools] [visualStates] Add JdeRobot logo to runtime gui

### ISSUE THREAD

**Issue by okanasik** [JdeRobot/JdeRobot#870]
We need to add JdeRobot logo to python and cpp runtime gui

**Comment by aitormf** [comment]
This issue is related to #660

**Comment by jmplaza** [comment]
Hi @okanasik, can this issue be closed?

**Comment by okanasik** [comment]
Hi @aitormf, yes this issue can be closed since new visualstates uses logo in runtime gui
