### ISSUE TITLE
[tools][uav_viewer_py] Confusion between config files

### ISSUE THREAD

**Issue by raulperula** [JdeRobot/JdeRobot#895]
Hi!

Trying to launch the _uav_viewer_py_ tool from the [example page](http://jderobot.org/index.php/Running_JdeRobot#Aerial_robots), by the command:

`uav_viewer uav_viewer_simulated.cfg
`

I have noticed that the config file that is included in the [tool folder](https://github.com/JdeRobot/JdeRobot/tree/master/src/tools/uav_viewer_py) is different and does not work:

`uav_viewer uav_viewer_py.cfg
`

Is this an error or simply a "residual" file?

**Comment by aitormf** [comment]
Hi @raulperula,

yes,  **uav_viewer_py.cfg** is a residual file. uav_viewer_py uses config files included in uav_viewer to reduce config files number

**Comment by raulperula** [comment]
Ok! So should I remove that file or could it be done by someone that has direct access to the repository. I think a pull request only for removing a file may be unnecessary.

**Comment by aitormf** [comment]
with new changes that allow us install uav_viewer_py without uav_viewer, we need a config file for uav_viewer_py. I will edit this file to fix it
