### ISSUE TITLE
[libs][jderobotcomm_py] Support for drone commands

### ISSUE THREAD

**Issue by raulperula** [JdeRobot/JdeRobot#896]
Hi!

I am trying to use the drone interfaces to control them but I have notice that there is no common interface implemented in the [library](https://github.com/JdeRobot/JdeRobot/tree/master/src/libs/jderobotcomm_py) yet.

Is it planned to be included?

At this moment, I am using directly the functions implemented in the _uav_viewer_py_ tool but adapted.

**Comment by aitormf** [comment]
Hi @raulperula,

yes, it is planned to include drone command to jderobotcomm_py (#679). The only thing we thought we'd do next month. After changing the configuration files  (#892) to not have to be modifying so many files when making this change.

If you need it already, we can change the order and include commads first

**Comment by raulperula** [comment]
No, it is ok for me. Once we have the new format for the config files I will update the Scratch2JdeRobot tool, and later, once the drone interface is added I simplify my code.

Thank you for all your comments @aitormf
