### ISSUE TITLE
[libs][jderobotcomm_py] bug in return?

### ISSUE THREAD

**Issue by raulperula** [JdeRobot/JdeRobot#897]
Hi!

I have noticed that in the code of the [jderobotcomm_py](https://github.com/JdeRobot/JdeRobot/blob/master/src/libs/jderobotcomm_py/jderobotComm/__init__.py) library the ROS node is returned:

```
...
	if (rosserver):
		node = rospy.init_node(nodeName, anonymous=True)

	return ic,node
...
```

But the [rospy API](http://docs.ros.org/kinetic/api/rospy/html/rospy-module.html#init_node) shows that there is nothing to return.

Does it has any sense to return it?

**Comment by aitormf** [comment]
Hi @raulperula,
Not is a bug. This function is prepared by the time that it generates ice communitacor and ros node.
In this way, customers are modified as little as possible

**Comment by raulperula** [comment]
Ok, thanks for the clarification. I think we can close the issue then.
