### ISSUE TITLE
[Tools] [VisualStates_py] CMake configure file creates files in build directory and created python file cannot be installed

### ISSUE THREAD

**Issue by okanasik** [JdeRobot/JdeRobot#906]
CMake configure file creates files in build directory and created python file cannot be installed. We should install the file relative to the CMAKE_CURRENT_BINARY_DIR directory.

**Comment by jmplaza** [comment]
This will be solved on the VisualStates [new repository](https://github.com/JdeRobot/VisualStates/issues/7)
