### ISSUE TITLE
[tools] VisualStates web page + examples

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/JdeRobot#944]
A page in the Tools section of JdeRobot webpage describing how to use VisualStates would help to new users who start using this tool, updating the [existing one](http://jderobot.org/VisualStates)

In addition, one or two small behaviors already programmed as example would clarify even more the use of VisualStates. They can be included in the src/examples/VisualStates directory, for instance, and a brief recipe in the [examples section of JdeRobot wepage](http://jderobot.org/index.php/Examples). One with TurtleBot robot in Gazebo and another with a drone.  

What do you think @okanasik ?

@jsaizc and @rafabernar are going to start using VisualStates to program drone behaviors.

**Comment by okanasik** [comment]
@jmplaza Thank you. Everything looks nice.
