### ISSUE TITLE
Master compilation fails -> yalm-cpp

### ISSUE THREAD

**Issue by chanfr** [JdeRobot/JdeRobot#952]
Hi all,
there is no Dep file for yaml-cpp and no reference to which package is necessary to compile jderobot with the new jderobot feature.

**Comment by aitormf** [comment]
Hi @chanfr, 

yaml-cpp is in following files of Deps: [https://github.com/JdeRobot/JdeRobot/blob/master/Deps/yaml-cpp/CMakeLists.txt](https://github.com/JdeRobot/JdeRobot/blob/master/Deps/yaml-cpp/CMakeLists.txt)

**Comment by chanfr** [comment]
hI @aitormf,
sorry about the delay.

ok, should it be a ERROR instead a simple message?

**Comment by aitormf** [comment]
ok, I will update it

**Comment by chanfr** [comment]
perfect!
