### ISSUE TITLE
Bumper support is required in Comm library

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/JdeRobot#956]
It is used in one [exercise of JdeRobot-Academy about Roomba](https://github.com/JdeRobot/Academy/tree/master/src/vacuum_cleaner). Maybe taking a look at ROS similar driver would help to shape this Comm interface in a similar way, and map it not only to current existing ICE plugin, but also to ROS plugin for TurtleBot or ROS driver for real TurtleBot.

**Comment by jmplaza** [comment]
Let's include a timestamp in this new interface, as we are going to include it in most sensor interfaces.

**Comment by aitormf** [comment]
solved with #966
