### ISSUE TITLE
[Gazebo] Several configuration files missing for "simpleCircuitObstacles.world"

### ISSUE THREAD

**Issue by cawadall** [JdeRobot/JdeRobot#958]
This is the output when trying to run it:
$ gazebo simpleCircuitObstacles.world

Load: 1496678224 f1::camera_top_body_left::cam_f1_left
Load: 315815704 f1::camera_top_body_right::cam_f1_right
LaserDump Constructor
constructor motors
-----------------constructor Pose3D
--Ice.Config=f1Motors.cfg
GetName() Pose3D: f1
easyice/loader.cpp:51: Ice::FileException:
file exception: couldn't open file
path: f1Motors.cfg
easyice/loader.cpp:51: Ice::FileException:
file exception: couldn't open file
path: f1Pose3D.cfg
 laser: f1::laser
strs[0]: f1
easyice/loader.cpp:51: Ice::FileException:
file exception: couldn't open file
path: f1_laser.cfg
 camera: f1::camera_top_body_left::cam_f1_left
easyice/loader.cpp:51: Ice::FileException:
file exception: couldn't open file
path: cam_f1_left.cfg
 camera: f1::camera_top_body_right::cam_f1_right
easyice/loader.cpp:51: Ice::FileException:
file exception: couldn't open file
path: cam_f1_right.cfg

**Comment by aitormf** [comment]
This a problem with instalation of those config files. 
It will be solved in the next release, meanwhile copy cfg files from **src/driver/gazeboserver/plugins/f1** to **/opt/jderobot/share/jderobot/conf**
