### ISSUE TITLE
[tools] Scratch2JdeRobot wiki including a list of supported blocks

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/JdeRobot#960]
Not only new Scratch blocks created in this tool (like those for drones, cameras, TurtleBot...), but also the general blocks of the language already supported in the tool

**Comment by scarrionv** [comment]
Added new section with generals blocks supported in the tool:
[http://jderobot.org/Scratch2JdeRobot#Blocks_included_in_Scratch](url)

**Comment by jmplaza** [comment]
Great!
