### ISSUE TITLE
[libs] [comm_py] publisherMotors gives undefined variable error when using sendW()

### ISSUE THREAD

**Issue by okanasik** [JdeRobot/JdeRobot#971]
publisherMotors gives undefined variable error when using sendW()

This is due to a very small error on the 174th line of https://github.com/JdeRobot/JdeRobot/blob/master/src/libs/comm_py/comm/ros/publisherMotors.py 

It should be `self.data.az = az`

**Comment by fqez** [comment]
solved, thanks!
